services:
  ml-services:
    image: "kevin1252/ml-grain-wise:1.2"
    env_file:
      - env
    volumes:
      - ./models:/ml-services/models

  web:
    # build: .
    image: 'kevin1252/grain-wise:1.2'
    volumes:
      - ./images:/dfg/images
      - ./storage:/dfg/storage
      - ./tmp:/tmp
    ports:
      - "9000:3000"
    env_file:
      - env

  redis:
    image: "redis:alpine"
  db:
    image: "kevin1252/grain-db:1.2"
    environment:
      POSTGRES_PASSWORD: root110120

